# Generated by Django 4.1.6 on 2023-02-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.ImageField(max_length=10, upload_to='')),
                ('subject', models.TextField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
